<?php
$a[]="Abdicate,high office or dignity";
$a[]="Adolescene,period of life from puberty to maturity";
$a[]="Amnesty,general pardon";
$a[]="Ad hoc,concerned with one specific purpose";
$a[]="Agnostic,one who believes nothing known about god";
$a[]="Altruist,habitual kind to others";
$a[]="Aphorism,a wise saying in a few words";
$a[]="Armistice,an agreement to stop fighting";
$a[]="Biennial,happening once every two year";
$a[]="Bon Vivant,one who likes good wine,food and company";
$a[]="Ascetic,one who avoids physical pleasure comforts";
$a[]="Celestial,of the sky or heaven";
$a[]="Cradle,a small bed for the baby";
$a[]="Colloquial,Suitable for ordinary,informal or familar conversation";
$a[]="Debacle,a sudden complete faliure";
$a[]="Embargo,official order forbiding trade with another country";
$a[]="Ergonomics,condition of working efficiently with machines";
$a[]="Expletive,often meaningless word used for swearing";
$a[]="Farrier,one who makes or fits shoes for horses";
$a[]="Foreman,a skilled and experienced worker in charger of other workers";
$a[]="Frill,a decorative edge to a piece of material";
$a[]="Gorge,a deep narrow valley with steep sides";
$a[]="Glut,a larger supply than is necessary";
$a[]="Heirloom,a valuable object passed on for generations";
$a[]="Innate,that which one is born with";
$a[]="Livery,uniform of a special type for servants";
$a[]="Odoriferous,having a smell, especially a pleasent one";
$a[]="Palaeography,the study of ancient writing";
$a[]="Plebeian,of the lower social classes";
$a[]="Pedantic,minute details of formalism";
$q=$_GET["rand"];
echo $a[$q];
?>